

### get tooele tech route

GET http://localhost:3000/ttech HTTP/1.1

### Get the route path

GET http://localhost:3000/ HTTP/1.1

### Get all students
GET http://localhost:3000/students HTTP/1.1  

@studentId = 69c17b2af8876aac5effe359

### Get one student
GET http://localhost:3000/students/{{studentId}} HTTP/1.1

### Create a student
POST http://localhost:3000/students HTTP/1.1
Content-Type: application/json

{
    "firstName": "Carl",
    "lastName": "Doe",
    "email": "Carl.doe@example.com",
    "age": 20,
    "currentCollege": "Colleg Academy"
} 

### Update a student

PUT http://localhost:3000/students/{{studentId}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "Carl",
    "lastName": "Doe Updated",
    "email": "Carl.doe@example.com",
    "age": 21,
    "currentCollege": "This is to test the update function"
}


### Delete a student

DELETE http://localhost:3000/students/{{studentId}} HTTP/1.1

### Register
POST http://localhost:3001/auth/register HTTP/1.1
Content-Type: application/json

{
    "fullName": "Test User",
    "email": "test@example.com",
    "password": "Password123!",
    "userType": "student"
}

### Login
POST http://localhost:3001/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "Password123!"
}

### Logout
POST http://localhost:3001/auth/logout HTTP/1.1
Content-Type: application/json

{}


@token = <your_token_here>
### Protected route with token
GET http://localhost:3001/auth/protected HTTP/1.1
Authorization: Bearer {{token}}