### get tooele tech route

GET http://localhost:3000/ttech HTTP/1.1

### Get the route path

GET http://localhost:3000/ HTTP/1.1

### Get all students
GET http://localhost:3000/students HTTP/1.1  

@studentId = REPLACE_WITH_REAL_ID

### Get one student
GET http://localhost:3000/students/{{studentId}} HTTP/1.1

### Create a student
POST http://localhost:3000/students HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "age": 20,
    "currentCollege": "StandIn Academy"
} 

## Update a student

PUT http://localhost:3000/students/{{studentId}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe Updated",
    "email": "john.doe@example.com",
    "age": 21,
    "currentCollege": "StandIn Academy"
}

## Delete a student

DELETE http://localhost:3000/students/{{studentId}} HTTP/1.1
